name: OFAC Monitor Scheduled Run

on:
  schedule:
    # 每天北京时间8点到20点，每隔1小时执行一次
    - cron: '0 0-12 * * *'  # UTC时间，对应北京时间早8点到晚8点，0点是0分
  workflow_dispatch:  # 允许手动触发

jobs:
  run-ofac-monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install

      - name: Run OFAC Monitor script
        env:
          FROM_ADDR: ${{ secrets.FROM_ADDR }}
          TO_ADDR: ${{ secrets.TO_ADDR }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        run: |
          python ofac_monitor.py
