name: OFAC Monitor Scheduled Run

on:
  schedule:
    # 每天北京时间 8:00 到 20:00，每小时运行一次（UTC时间0点-12点）
    - cron: '0 0-12 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  run-ofac-monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install

      - name: Run OFAC Monitor script
        env:
          FROM_ADDR: ${{ secrets.FROM_ADDR }}
          TO_ADDR: ${{ secrets.TO_ADDR }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        run: python ofac_monitor.py
