name: OFAC Monitor Scheduled Run

on:
  schedule:
    # 每小时 UTC 跑一次（等于美东时间 每小时 7am-8pm 等区间内都能跑）
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  run-ofac-monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run OFAC Monitor script
        env:
          RESET_NOTIFICATION: "1"  # ✅ 开启每次运行都清除 ofac_sent.log
          FROM_ADDR: ${{ secrets.FROM_ADDR }}
          TO_ADDR: ${{ secrets.TO_ADDR }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        run: python ofac_monitor.py
